### ISSUE TITLE
WooCommerce database update not taking hold/failing

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_PDS#16]
https://peacefuldragonschool.com/wp-admin/admin.php?page=wc-status&tab=action-scheduler&s=woocommerce_run_update&status=pending

I've attempted the update three times. No luck.

**Comment by d4mation** [comment]
Seemed to work for me? Maybe there were multiple database upgrades that needed applied? 

![image](https://user-images.githubusercontent.com/7770631/165127614-9c2c0d0e-85ec-450a-8390-3adc99c1a839.png)
