### ISSUE TITLE
Password reset link in email just shows the reset form

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_PDS#3]
This has been a major source of annoyance for the client. What happens is a user goes to the login, clicks on the Forgot Password link and gets redirected to the WooCommerce password reset page. There they put in their email address and get sent a WooCommerce email with a link to reset the password. This goes back to the exact same page which shows the field asking for their email address which means they are stuck in a loop and are _never actually able to reset their password_.

**Comment by d4mation** [comment]
SOLVED!

https://wordpress.org/support/topic/reset-password-loop/

If this is ever a problem in the future on any other sites, WP Engine will need to whitelist the URL from caching.
